compilers:
  - name: "clang"
    version: "3.5"
    cmake_extra_flags: -DBUILD_TESTING:BOOL=ON -DBUILD_SWIG:BOOL=ON -DBUILD_BOOST:BOOL=OFF -DBUILD_QT:BOOL=OFF -DBUILD_RUBY:BOOL=OFF
  - name: cppcheck
    compiler_extra_flags: --enable=warning  --suppress="*:*zlib*" --suppress="*:*sqlite*" --suppress="cppcheckError:*" --inline-suppr --suppress="syntaxError:*"
