stages:
- buildDView
- buildOS

buildDView:windows:
  variables:
    #CI_DEBUG_TRACE: "true"
  stage: buildDView
  only:
  - develop
  tags:
  - windows
  script:
  - if not exist "buildMeta" mkdir buildMeta
  - cd buildMeta
  - cmake -G "Visual Studio 12 2013 Win64" ..
  - cmake -DBUILD_DVIEW=ON -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --config Release --target DView
  artifacts:
    expire_in: 12 hrs
    paths:
      - buildMeta/DView-prefix/src/DView-install

buildDView:mac:
  variables:
    #CI_DEBUG_TRACE: "true"
  stage: buildDView
  only:
  - develop
  tags:
  - mac
  script:
  - mkdir -p buildMeta
  - cd buildMeta
  - cmake ..
  - cmake -DBUILD_DVIEW=ON -DCMAKE_BUILD_TYPE=Release ..
  - make -j8 DView
  artifacts:
    expire_in: 12 hrs
    paths:
      - buildMeta/DView-prefix/src/DView-install
      
buildDView:ubuntu:
  variables:
    #CI_DEBUG_TRACE: "true"
  stage: buildDView
  only:
  - develop
  tags:
  - ubuntu
  script:
  - mkdir -p buildMeta
  - cd buildMeta
  - cmake ..
  #- cmake -DBUILD_DVIEW=ON -DCMAKE_BUILD_TYPE=Release ..
  #- make -j8 DView
  #artifacts:
  #  expire_in: 12 hrs
  #  paths:
  #    - buildMeta/DView-prefix/src/DView-install
      
buildOS:windows:
  variables:
    #CI_DEBUG_TRACE: "true"
  stage: buildOS
  only:
  - develop
  tags:
  - windows
  script:
  - if not exist "build" mkdir build
  - cd build
  - cmake -G "Visual Studio 12 2013 Win64" ../openstudiocore
  - cmake -DBUILD_CSHARP_BINDINGS=ON -DBUILD_DOCUMENTATION=ON -DBUILD_TESTING=ON -DBUILD_DVIEW=ON -DBUILD_OS_APP=ON -DBUILD_PACKAGE=ON -DBUILD_PAT=ON -DCMAKE_BUILD_TYPE=Release -DCPACK_BINARY_DEB=OFF -DCPACK_BINARY_IFW=ON -DCPACK_BINARY_NSIS=OFF -DCPACK_BINARY_RPM=OFF -DCPACK_BINARY_STGZ=OFF -DCPACK_BINARY_TBZ2=OFF -DCPACK_BINARY_TGZ=OFF -DCPACK_BINARY_TXZ=OFF -DCPACK_BINARY_TZ=OFF ../openstudiocore
  - cmake ../openstudiocore
  - cmake --build . --config Release --target PACKAGE
  artifacts:
    expire_in: 12 hrs
    paths:
      - build/
 
buildOS:mac:
  variables:
    #CI_DEBUG_TRACE: "true"
  stage: buildOS
  only:
  - develop
  tags:
  - mac
  script:
  - mkdir -p build
  - cd build
  - cmake ../openstudiocore
  - cmake -DOPENSSL_INCLUDE_DIR=/usr/bin/openssl -DBUILD_DVIEW=ON -DBUILD_OS_APP=ON -DBUILD_PACKAGE=ON -DBUILD_PAT=ON -DCMAKE_BUILD_TYPE=Release -DCPACK_BINARY_DEB=OFF -DCPACK_BINARY_IFW=ON -DCPACK_BINARY_NSIS=OFF -DCPACK_BINARY_RPM=OFF -DCPACK_BINARY_STGZ=OFF -DCPACK_BINARY_TBZ2=OFF -DCPACK_BINARY_TGZ=OFF -DCPACK_BINARY_TXZ=OFF -DCPACK_BINARY_TZ=OFF ../openstudiocore
  - cmake ../openstudiocore
  - make -j8 package
  artifacts:
    expire_in: 2 hrs
    paths:
      - build/_CPack_Packages/Darwin/IFW

buildOS:ubuntu:
  variables:
    #CI_DEBUG_TRACE: "true"
  stage: buildOS
  only:
  - develop
  tags:
  - ubuntu
  script:
  - mkdir -p build
  - cd build
  - cmake ../openstudiocore
  #- cmake -DOPENSSL_INCLUDE_DIR=/usr/bin/openssl -DBUILD_DVIEW=OFF -DBUILD_OS_APP=ON -DBUILD_PACKAGE=ON -DBUILD_PAT=OFF -DCMAKE_BUILD_TYPE=Release -DCPACK_BINARY_DEB=ON -DCPACK_BINARY_IFW=OFF -DCPACK_BINARY_NSIS=OFF -DCPACK_BINARY_RPM=OFF -DCPACK_BINARY_STGZ=OFF -DCPACK_BINARY_TBZ2=OFF -DCPACK_BINARY_TGZ=OFF -DCPACK_BINARY_TXZ=OFF -DCPACK_BINARY_TZ=OFF ../openstudiocore
  #- cmake ../openstudiocore
  #- make -j8 package
  #artifacts:
  #  expire_in: 2 hrs
  #  paths:
  #    - build/

testOSResources:windows:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: testOSResources
  only:
  - develop
  tags:
  - windows
  script:
  ##- cd build
  ##- OpenStudio-2.4.1.b75cf90df5-Windows.exe --script ../install.qs
  #- cd ../temp
  #- OpenStudio-2.4.1.b75cf90df5-Windows.exe --script ../OpenStudio/install.qs
  - "cd \"c:\\\""
  ##- if not exist "OpenStudio-resources" mkdir OpenStudio-resources
  ##- cd OpenStudio-resources
  - git clone https://github.com/NREL/OpenStudio-resources.git
  #- "cd \"c:\\openstudio\\bin\\\""
  #- "openstudio.exe c:\\OpenStudio-resources\\model_tests.rb"
