stages:
- buildOS
- deployOS

buildOS:windows:
  stage: buildOS
  only:
  - triggers
  tags:
  - windows
  script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 12 2013 Win64" -DBUILD_CSHARP_BINDINGS=ON -DBUILD_DOCUMENTATION=ON -DBUILD_TESTING=ON -DBUILD_DVIEW=OFF -DBUILD_OS_APP=ON -DBUILD_PACKAGE=ON -DBUILD_PAT=OFF -DCMAKE_BUILD_TYPE=Release -DCPACK_BINARY_DEB=OFF -DCPACK_BINARY_IFW=ON -DCPACK_BINARY_NSIS=OFF -DCPACK_BINARY_RPM=OFF -DCPACK_BINARY_STGZ=OFF -DCPACK_BINARY_TBZ2=OFF -DCPACK_BINARY_TGZ=OFF -DCPACK_BINARY_TXZ=OFF -DCPACK_BINARY_TZ=OFF -DCPACK_SOURCE_RPM=OFF -DCPACK_SOURCE_TBZ2=OFF -DCPACK_SOURCE_TGZ=0 -DCPACK_SOURCE_TXZ=0 -DCPACK_SOURCE_TZ=0 -DCPACK_SOURCE_ZIP=0 ../openstudiocore
  - cmake --build . --config Release --target ALL_BUILD
  - cmake --build . --config Release --target ALL_BUILD
  - cmake --build . --config Release --target PACKAGE
  retry: 1
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/OpenStudio-*.exe
 
buildOS:mac:
  stage: buildOS
  only:
  - triggers
  tags:
  - mac
  script:
  - mkdir build
  - cd build
  - cmake -DOPENSSL_INCLUDE_DIR=/usr/bin/openssl -DBUILD_DVIEW=ON -DBUILD_OS_APP=ON -DBUILD_PACKAGE=ON -DBUILD_PAT=ON -DCMAKE_BUILD_TYPE=Release -DCPACK_BINARY_DEB=OFF -DCPACK_BINARY_IFW=ON -DCPACK_BINARY_NSIS=OFF -DCPACK_BINARY_RPM=OFF -DCPACK_BINARY_STGZ=OFF -DCPACK_BINARY_TBZ2=OFF -DCPACK_BINARY_TGZ=OFF -DCPACK_BINARY_TXZ=OFF -DCPACK_BINARY_TZ=OFF ../openstudiocore
  - make -j16 package
  - cd _CPack_Packages/Darwin/IFW
  - ls
  - zip -r `ls -1 | grep OpenStudio-*.app | sed -e 's/\.app$//'`.zip OpenStudio-*.app
  retry: 1
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/_CPack_Packages/Darwin/IFW/OpenStudio-*.zip

buildOS:ubuntu:
  stage: buildOS
  only:
  - triggers
  tags:
  - ubuntu
  script:
  - mkdir build
  - cd build
  - cmake -DOPENSSL_INCLUDE_DIR=/usr/bin/openssl -DBUILD_DVIEW=OFF -DBUILD_OS_APP=ON -DBUILD_PACKAGE=ON -DBUILD_PAT=OFF -DCMAKE_BUILD_TYPE=Release -DCPACK_BINARY_DEB=ON -DCPACK_BINARY_IFW=OFF -DCPACK_BINARY_NSIS=OFF -DCPACK_BINARY_RPM=OFF -DCPACK_BINARY_STGZ=OFF -DCPACK_BINARY_TBZ2=OFF -DCPACK_BINARY_TGZ=OFF -DCPACK_BINARY_TXZ=OFF -DCPACK_BINARY_TZ=OFF ../openstudiocore
  - make -j16 package
  retry: 1
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/OpenStudio-*.deb

deployOS:windows:
  stage: deployOS
  only:
  - triggers
  tags:
  - windows
  dependencies:
  - buildOS:windows
  script:
  - cd build
  - dir
  - aws s3 cp ./ s3://openstudio-builds/CI/ --recursive --exclude "*" --include "*.exe"

deployOS:mac:
  stage: deployOS
  only:
  - triggers
  tags:
  - mac
  dependencies:
  - buildOS:mac
  script:
  - cd build/_CPack_Packages/Darwin/IFW
  - ls
  - aws s3 cp ./ s3://openstudio-builds/CI/ --recursive --exclude "*" --include "*.zip"

deployOS:ubuntu:
  stage: deployOS
  only:
  - triggers
  tags:
  - ubuntu
  dependencies:
  - buildOS:ubuntu
  script:
  - cd build
  - ls
  - aws s3 cp ./ s3://openstudio-builds/CI/ --recursive --exclude "*" --include "*.deb"  
