stages:
- buildDView
- deployDView
- buildOS
- deployOS
- testOSResources

buildDView:windows:
  #variables:
  #  CI_DEBUG_TRACE: "true"
  stage: buildDView
  only:
  - develop
  tags:
  - windows
  script:
  - mkdir buildMeta
  - cd buildMeta
  - cmake -G "Visual Studio 12 2013 Win64" -DBUILD_DVIEW=ON -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --config Release --target DView
  artifacts:
    expire_in: 6 hrs
    paths:
      - buildMeta/DView-prefix/src/DView-install

buildDView:mac:
  #variables:
  #  CI_DEBUG_TRACE: "true"
  stage: buildDView
  only:
  - develop
  tags:
  - mac
  script:
  - mkdir buildMeta
  - cd buildMeta
  - cmake -DBUILD_DVIEW=ON -DCMAKE_BUILD_TYPE=Release ..
  - make -j16 DView
  artifacts:
    expire_in: 6 hrs
    paths:
      - buildMeta/DView-prefix/src/DView-install
      
buildDView:ubuntu:
  #variables:
  #  CI_DEBUG_TRACE: "true"
  stage: buildDView
  only:
  - develop
  tags:
  - ubuntu
  script:
  - mkdir buildMeta
  - cd buildMeta
  #- cmake -DBUILD_DVIEW=ON -DCMAKE_BUILD_TYPE=Release ..
  #- make -j16 DView
  #artifacts:
  #  expire_in: 6 hrs
  #  paths:
  #    - buildMeta/DView-prefix/src/DView-install

deployDView:windows:
  #variables:
  #  CI_DEBUG_TRACE: "true"
  stage: deployDView
  only:
  - develop
  tags:
  - windows
  dependencies:
  - buildDView:windows
  script:
  - C:/Python27/Scripts/aws --version
  - cd  buildMeta/DView-prefix/src/DView-install
  - C:/Python27/Scripts/aws s3 cp ./ s3://openstudio-builds/CI/ --recursive --exclude "*" --include "DView.exe"

deployDView:mac:
  #variables:
  #  CI_DEBUG_TRACE: "true"
  stage: deployDView
  only:
  - develop
  tags:
  - mac
  dependencies:
  - buildDView:mac
  script:
  - cd  buildMeta/DView-prefix/src/DView-install
  - aws --version
  - aws s3 cp ./ s3://openstudio-builds/CI/ --recursive --exclude "*" --include "DView"

deployDView:ubuntu:
  #variables:
  #  CI_DEBUG_TRACE: "true"
  stage: deployDView
  only:
  - develop
  tags:
  - ubuntu
  dependencies:
  - buildDView:ubuntu
  script:
  - ls
  #- aws --version
  #- cd  buildMeta/DView-prefix/src/DView-install
  #- aws s3 cp ./ s3://openstudio-builds/CI/ --recursive --exclude "*" --include "DView.???"

buildOS:windows:
  #variables:
  #  CI_DEBUG_TRACE: "true"
  stage: buildOS
  only:
  - develop
  tags:
  - windows
  dependencies:
  - deployDView:windows
  script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 12 2013 Win64" -DBUILD_CSHARP_BINDINGS=ON -DBUILD_DOCUMENTATION=ON -DBUILD_TESTING=ON -DBUILD_DVIEW=OFF -DBUILD_OS_APP=ON -DBUILD_PACKAGE=ON -DBUILD_PAT=ON -DCMAKE_BUILD_TYPE=Release -DCPACK_BINARY_DEB=OFF -DCPACK_BINARY_IFW=ON -DCPACK_BINARY_NSIS=OFF -DCPACK_BINARY_RPM=OFF -DCPACK_BINARY_STGZ=OFF -DCPACK_BINARY_TBZ2=OFF -DCPACK_BINARY_TGZ=OFF -DCPACK_BINARY_TXZ=OFF -DCPACK_BINARY_TZ=OFF -DCPACK_SOURCE_RPM=OFF -DCPACK_SOURCE_TBZ2=OFF -DCPACK_SOURCE_TGZ=0 -DCPACK_SOURCE_TXZ=0 -DCPACK_SOURCE_TZ=0 -DCPACK_SOURCE_ZIP=0 ../openstudiocore
  - cmake --build . --config Release --target ALL_BUILD
  - cmake --build . --config Release --target ALL_BUILD
  - cmake --build . --config Release --target PACKAGE
  retry: 1
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/OpenStudio-*.exe
 
buildOS:mac:
  #variables:
  #  CI_DEBUG_TRACE: "true"
  stage: buildOS
  only:
  - develop
  tags:
  - mac
  dependencies:
  - deployDView:mac
  script:
  - mkdir build
  - cd build
  - cmake -DOPENSSL_INCLUDE_DIR=/usr/bin/openssl -DBUILD_DVIEW=ON -DBUILD_OS_APP=ON -DBUILD_PACKAGE=ON -DBUILD_PAT=ON -DCMAKE_BUILD_TYPE=Release -DCPACK_BINARY_DEB=OFF -DCPACK_BINARY_IFW=ON -DCPACK_BINARY_NSIS=OFF -DCPACK_BINARY_RPM=OFF -DCPACK_BINARY_STGZ=OFF -DCPACK_BINARY_TBZ2=OFF -DCPACK_BINARY_TGZ=OFF -DCPACK_BINARY_TXZ=OFF -DCPACK_BINARY_TZ=OFF ../openstudiocore
  - make -j16 package
  - cd _CPack_Packages/Darwin/IFW
  - zip -r OpenStudio*.zip OpenStudio*
  retry: 1
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/_CPack_Packages/Darwin/IFW/OpenStudio-*.zip

buildOS:ubuntu:
  #variables:
  #  CI_DEBUG_TRACE: "true"
  stage: buildOS
  only:
  - develop
  tags:
  - ubuntu
  dependencies:
  - deployDView:ubuntu
  script:
  - mkdir build
  - cd build
  - cmake -DOPENSSL_INCLUDE_DIR=/usr/bin/openssl -DBUILD_DVIEW=OFF -DBUILD_OS_APP=ON -DBUILD_PACKAGE=ON -DBUILD_PAT=OFF -DCMAKE_BUILD_TYPE=Release -DCPACK_BINARY_DEB=ON -DCPACK_BINARY_IFW=OFF -DCPACK_BINARY_NSIS=OFF -DCPACK_BINARY_RPM=OFF -DCPACK_BINARY_STGZ=OFF -DCPACK_BINARY_TBZ2=OFF -DCPACK_BINARY_TGZ=OFF -DCPACK_BINARY_TXZ=OFF -DCPACK_BINARY_TZ=OFF ../openstudiocore
  - make -j16 package
  retry: 1
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/OpenStudio-*.deb

deployOS:windows:
  #variables:
  #  CI_DEBUG_TRACE: "true"
  stage: deployOS
  only:
  - develop
  tags:
  - windows
  dependencies:
  - buildOS:windows
  script:
  - C:/Python27/Scripts/aws s3 cp ./ s3://openstudio-builds/CI/ --recursive --exclude "*" --include "*.exe"

deployOS:mac:
  #variables:
  #  CI_DEBUG_TRACE: "true"
  stage: deployOS
  only:
  - develop
  tags:
  - mac
  dependencies:
  - buildOS:mac
  script:
  - cd  build/_CPack_Packages/Darwin/IFW/
  - aws s3 cp ./ s3://openstudio-builds/CI/ --recursive --exclude "*" --include "*.zip"

deployOS:ubuntu:
  #variables:
  #  CI_DEBUG_TRACE: "true"
  stage: deployOS
  only:
  - develop
  tags:
  - ubuntu
  dependencies:
  - buildOS:ubuntu
  script:
  - aws s3 cp ./ s3://openstudio-builds/CI/ --recursive --exclude "*" --include "*.dmg"  

testOSResources:windows:
  #variables:
  #  CI_DEBUG_TRACE: "true"
  stage: testOSResources
  only:
  - develop
  tags:
  - windows
  dependencies:
  - buildOS:windows
  script:
  ##- cd build
  ##- OpenStudio-2.4.1.b75cf90df5-Windows.exe --script ../install.qs
  #- cd ../temp
  #- OpenStudio-2.4.1.b75cf90df5-Windows.exe --script ../OpenStudio/install.qs
  - "cd \"c:\\\""
  ##- if not exist "OpenStudio-resources" mkdir OpenStudio-resources
  ##- cd OpenStudio-resources
  - git clone https://github.com/NREL/OpenStudio-resources.git
  #- "cd \"c:\\openstudio\\bin\\\""
  #- "openstudio.exe c:\\OpenStudio-resources\\model_tests.rb"

  