stages:
- build
- deploy
- testCTest
- testResources

build:windows:
  stage: build
  only:
  - triggers
  - master
  - develop
  tags:
  - windows
  script:
  - rd /s /q build
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 12 2013 Win64" -DBUILD_CSHARP_BINDINGS=ON -DBUILD_DOCUMENTATION=ON -DBUILD_TESTING=ON -DBUILD_DVIEW=ON -DBUILD_OS_APP=ON -DBUILD_PACKAGE=ON -DBUILD_PAT=OFF -DCMAKE_BUILD_TYPE=Release -DCPACK_BINARY_DEB=OFF -DCPACK_BINARY_IFW=ON -DCPACK_BINARY_NSIS=OFF -DCPACK_BINARY_RPM=OFF -DCPACK_BINARY_STGZ=OFF -DCPACK_BINARY_TBZ2=OFF -DCPACK_BINARY_TGZ=OFF -DCPACK_BINARY_TXZ=OFF -DCPACK_BINARY_TZ=OFF  ../openstudiocore
  - cmake --build . --config Release --target ALL_BUILD
  - cmake --build . --config Release --target ALL_BUILD
  - cmake --build . --config Release --target PACKAGE
  allow_failure: true
  artifacts:
    expire_in: 12 hrs
    paths:
    - build/OpenStudio-*.exe
    - build/CPackConfig.cmake
    - build/CPackSourceConfig.cmake
    - build/CTestTestfile.cmake
    - build/OpenStudioCoreConfig.cmake
    - build/CTestTestfile.cmake
    - build/csharp/
    - build/embedded/
    - build/pat/
    - build/Products/
    - build/resources/
    - build/ruby/
    - build/sketchup_plugin/
    - build/src/

build:mac:
  stage: build
  only:
  - triggers
  - master
  - develop
  tags:
  - mac
  script:
  - mkdir build
  - cd build
  - cmake -DOPENSSL_INCLUDE_DIR=/usr/bin/openssl -DBUILD_DVIEW=ON -DBUILD_OS_APP=ON -DBUILD_PACKAGE=ON -DBUILD_PAT=OFF -DCMAKE_BUILD_TYPE=Release -DCPACK_BINARY_DEB=OFF -DCPACK_BINARY_IFW=ON -DCPACK_BINARY_NSIS=OFF -DCPACK_BINARY_RPM=OFF -DCPACK_BINARY_STGZ=OFF -DCPACK_BINARY_TBZ2=OFF -DCPACK_BINARY_TGZ=OFF -DCPACK_BINARY_TXZ=OFF -DCPACK_BINARY_TZ=OFF ../openstudiocore
  - make -j16 package
  - cd _CPack_Packages/Darwin/IFW
  - zip -r `ls -1 | grep OpenStudio-*.app | sed -e 's/\.app$//'`.zip OpenStudio-*.app
  allow_failure: true
  artifacts:
    expire_in: 12 hrs
    paths:
      - build/_CPack_Packages/Darwin/IFW/OpenStudio-*.zip

build:ubuntu:
  stage: build
  only:
  - triggers
  - master
  - develop
  tags:
  - ubuntu
  script:
  - mkdir build
  - cd build
  - cmake -DOPENSSL_INCLUDE_DIR=/usr/bin/openssl -DBUILD_DVIEW=OFF -DBUILD_OS_APP=ON -DBUILD_PACKAGE=ON -DBUILD_PAT=OFF -DCMAKE_BUILD_TYPE=Release -DCPACK_BINARY_DEB=ON -DCPACK_BINARY_IFW=OFF -DCPACK_BINARY_NSIS=OFF -DCPACK_BINARY_RPM=OFF -DCPACK_BINARY_STGZ=OFF -DCPACK_BINARY_TBZ2=OFF -DCPACK_BINARY_TGZ=OFF -DCPACK_BINARY_TXZ=OFF -DCPACK_BINARY_TZ=OFF ../openstudiocore
  - make -j16 package
  allow_failure: true
  artifacts:
    expire_in: 12 hrs
    paths:
      - build/OpenStudio-*.deb

deploy:windows:
  stage: deploy
  only:
  - triggers
  - master
  - develop
  tags:
  - windows
  dependencies:
  - build:windows
  script:
  - cd build
  - aws s3 cp ./ s3://openstudio-builds/PR/ --exclude "*" --include "*.exe"
  allow_failure: true

deploy:mac:
  stage: deploy
  only:
  - triggers
  - master
  - develop
  tags:
  - mac
  dependencies:
  - build:mac
  script:
  - cd build/_CPack_Packages/Darwin/IFW
  - aws s3 cp ./ s3://openstudio-builds/PR/ --exclude "*" --include "*.zip"
  allow_failure: true

deploy:ubuntu:
  stage: deploy
  only:
  - triggers
  - master
  - develop
  tags:
  - ubuntu
  dependencies:
  - build:ubuntu
  script:
  - cd build
  - aws s3 cp ./ s3://openstudio-builds/PR/ --exclude "*" --include "*.deb"
  allow_failure: true

testCTest:windows:
  stage: testCTest
  only:
  - triggers
  - master
  - develop
  tags:
  - windows
  dependencies:
  - build:windows
  script:
  - cd build
  - dir
  - CTest
  allow_failure: true

testResources:windows:
  stage: testResources
  only:
  - triggers
  - master
  - develop
  tags:
  - windows
  dependencies:
  - build:windows
  script:
  - "rmdir c:\\\\openstudio\\ /s /q"
  - cd build
  - dir
  - xcopy *.exe win.exe*
  - dir
  - win.exe --script ../install.qs
  - cd c://openstudio/
  - git clone https://github.com/NREL/OpenStudio-resources.git
  - cd bin/
  - openstudio.exe ../OpenStudio-resources/model_tests.rb"
  allow_failure: true # To allow for CTest failures above

